# Assignment 1
By the end of this first assignment you will be able to
1. Use Python and Jupyter notebooks as a calculator
1. Describe and use basic data types for mathematics
1. Use Numpy package for creating arrays of numbers and doing calculations
1. Create scatter and line plots
1. Apply basic formatting to graphs, such as color, data point shape, x and y labels, x and y limits
1. Import a data set as a Numpy Array
1. Learn how to index (select particular rows and colums) within a data set (for plotting and analysis)
1. Learn how to add formatting and commentary to your Jupyter notebook using markdown

## Using Python and Jupyer Notebooks as a calculator

In [14]:
3+2.5  # hit shift+enter to execute a cell

5.5

In [2]:
2**3 # notice only the last output is printed
2**4

16

In [3]:
print(2**3) # adding a print() function around the calculation make sure it is printed (though it isn't an Out[N])
2**4

8


16

Calculate $\frac{(3-4)^2-8\times17}{5}$

In [4]:
(3-4)

-1

## Using Python as a calculator for physics problems
Consider this totally typical UP1 problem (copied from the 2016 UP1 activity manual)

1. A ball is thrown upwards at 9 m/s toward a platform located 4.1 m above the point where you release the ball. Air resistance is negligable. *Find the time taken to reach the platform.*


Two approaches to using Python as a calculator
* Plug numbers directly into the equation
* Define the constants and parameters, then symbolically write out the equation.

I'll use displacement as a function of time $y = y_0 + v_{y0}t + \frac{1}{2}at^2$ and solve using the quadratic equation.

In [5]:
print( ((-9) + (9**2 - 4*(-9.8/2)*(0-4.1))**0.5)/(2*(-9.8/2)) ) # one root
print( ((-9) - (9**2 - 4*(-9.8/2)*(0-4.1))**0.5)/(2*(-9.8/2)) ) # the other root


0.8367346938775508
1.0


In [6]:
y0 = 0
yf = 4.1
vy0 = 9
a = -9.8
print( (-vy0 + ( vy0**2 - 4*(0.5*a)*(y0-yf) )**0.5)/( 2*0.5*a ) )
print( (-vy0 - ( vy0**2 - 4*(0.5*a)*(y0-yf) )**0.5)/( 2*0.5*a ) )
t1 = (-vy0 + ( vy0**2 - 4*(0.5*a)*(y0-yf) )**0.5)/( 2*0.5*a)

0.8367346938775508
1.0


### Tasks

1. What are some pros or cons of the two different approaches? (Type your answer into a Markdown cell)
2. For the same situation as above (ball thrown upward), *find the velocity when the ball reaches the platform.* (Use approach 2 where you define the variables). Note that the variables defined in one cell are accessible in all other cells.

## Basic data types in Python

* **integers**, such as `-1`, `0`, `2`, `3`, 
* **floats** (decimal numbers stored in scientific notation), such as `3.14`, `5e8`, `-2.2002`
* **strings**, such as  `"happy"`, `"birthday"`, `"spaces are okay too, and punctuation."`
* **lists** of similar objects go in square brackets, such as `[1,2,3]` or `["happy", "birthday", "to", "you"]` 

In [7]:
2 + 2 # addition, subtraction, multiplication works okay for integers

4

In [8]:
ltest = [7,10,-4,23] # creating a list of integers
print(ltest)
ltest[0] # access each element of a list using an index in square brackets, indexing starts at 0

[7, 10, -4, 23]


7

### Tasks
Insert one or more cells below and answer these questions.
1. What happens when you do division with integers (for example, `3/2`, `17/5`)?
1. If you have a calculation with an integer AND a float (for example `2*3.1415`) what data type is the output?
1. Use scientific notation (e-notation) to define some basic physics constants, like $\hbar$ and the electron charge $e$. 
1. Access the 4th element in the list `ltest` defined above

## Using Numpy package to create arrays of numbers for calculations

Often times for calculations you want an array of numbers that spans some range of values. And then you want do do calculations on all those values. Scipy has a package Numpy (numerical python) that is used for array and matrix math. It required importing the numpy package to access all the functions.

In [5]:
import numpy as np # you only need to import a package once in your notebook (usually best at the very top)

In [10]:
# now a bunch of new functions are accessible

x = np.linspace(0,10, 101)  # make an array that starts at 0, ends at 10, and takes 101 steps.
print(x)

[  0.    0.1   0.2   0.3   0.4   0.5   0.6   0.7   0.8   0.9   1.    1.1
   1.2   1.3   1.4   1.5   1.6   1.7   1.8   1.9   2.    2.1   2.2   2.3
   2.4   2.5   2.6   2.7   2.8   2.9   3.    3.1   3.2   3.3   3.4   3.5
   3.6   3.7   3.8   3.9   4.    4.1   4.2   4.3   4.4   4.5   4.6   4.7
   4.8   4.9   5.    5.1   5.2   5.3   5.4   5.5   5.6   5.7   5.8   5.9
   6.    6.1   6.2   6.3   6.4   6.5   6.6   6.7   6.8   6.9   7.    7.1
   7.2   7.3   7.4   7.5   7.6   7.7   7.8   7.9   8.    8.1   8.2   8.3
   8.4   8.5   8.6   8.7   8.8   8.9   9.    9.1   9.2   9.3   9.4   9.5
   9.6   9.7   9.8   9.9  10. ]


Taking a subset of an array has a compact notation.

In [11]:
x[0:10]  #give me the elements starting at index 0 and ending (but not including) 10.

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [12]:
x[0:10:2] # give me the elements starting at index 0, ending at 10, but increment index by 2

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

### Tasks
1. What does array subset `x[-1:-10:-1]` do? Try it out and explain the results.
1. Look up the official numpy documentation. What is the difference between the the `linspace()` function and `arange()` function?
1. Create an array that goes between 0 and $4\pi$ in 100 steps using the `arange()` function.


In [13]:
pi = np.pi

## Creating scatter and line plots using Matplotlib package

In this course we will rely almost exclusively on the suite of plotting tools available in the matplotlib package. There is very good documentation and it is well-suited for scientific computing for physics.

In [4]:
import matplotlib.pyplot as plt  # use this import statement to access the most useful plotting tools

In [16]:
x = np.linspace(0,4*np.pi, 100)
y1 = np.sin(x)
y2 = np.cos(x)

plt.plot(x,y1)

In [3]:
# you can overlay two curves in the same figure by plotting both in the same cell
plt.plot(x,y1, label="sin")
plt.plot(x,y2, label="cos")
plt.legend()

NameError: name 'plt' is not defined

In [18]:
# formatting can be added as well
plt.plot(x,y1)
plt.xlabel("Time (s)")
plt.ylabel("Position (m)")
plt.title("Oscillation of a mass on a spring")

### Tasks
1. Using the official matplotlib documentation (Google it!), look up the `xlabel()` function. How can you increase the label font size to 14 point font?
1. Using the official matplotlib documentation, look up the `legend()` function. Redo the overlaid plot of $\sin(x)$ and $\cos(x)$ and label both curves (e.g. "sin" and "cos").

## Importing and plotting data

It is always a good idea to first view a data in a text editor to identify the column headings and column delimiter (column separator).

![screenshot of CSV file](screenshot_of_csv_file.JPG "Optional title")


### Tasks

1. Open the `torsion pendulum.csv` file on your own computer using a text editor.
  * How many columns in the data set?
  * How many header rows (rows used to label the columns)?
  * What separates the columns? 
  * What does the abbreviation CSV stand form?  

In [4]:
import os # imports a set of "operating system functions, for tasks like changing the current directory or listing files in a directory

In [21]:
os.getcwd()

'/home/user/assignments/Assignment1'

In [22]:
os.listdir()

['.Assignment1_intro.ipynb.sage-jupyter2',
 'Assignment1_intro.ipynb',
 'screenshot_of_csv_file.JPG',
 'torsion pendulum.csv']

### Import data using Numpy `loadtxt()` 
The `loadtxt()` function loads data from a text file into a numpy array.

In [6]:
data = np.loadtxt("torsion pendulum.csv", skiprows=1, delimiter=',')

In [8]:
# view the data (expect a lot of data!)
data

array([[ 0.01      , -0.98203003,  0.47622234, ...,  0.22094992,
         0.03803681, -0.21529192],
       [ 0.02      , -0.98204321,  0.49986541, ...,  0.22388087,
         0.03785476, -0.21517904],
       [ 0.03      , -0.64572388,  0.16007045, ...,  0.22567222,
         0.07210864, -0.22349128],
       ..., 
       [ 7.21999979,  0.14598948,  6.87409878, ..., -0.21646793,
        -0.04707724, -0.25885564],
       [ 7.23000002,  0.15691473,  6.86100245, ..., -0.20108864,
        -0.03501483, -0.27436966],
       [ 7.23999977,  0.049796  ,  6.87398386, ..., -0.18434399,
        -0.03746882, -0.26646158]])

### Taking subsets of arrays
The array of data is two dimensional (2D). It has row and columns. 

    data[n,m]  # returns entry in the n-th row, m-th column
    data[:,m]  # the colon : means returns all rows, mth column

In [9]:
t = data[:,0]  # the first column is time (according to the header row)
ax = data[:,1] # the second column is x-component of acceleration

In [10]:
plt.plot(t,ax)

### Tasks
1. How many columns are there all together? 
1. Create additional variable names for the other rows. Pick names that align with the column header (seen in the .csv file).
1. Create a plot of the 5th column vs time. Label the axes.
1. In the plot you just made, what is going on physically based on the data? 

## Formatting a Jupyter notebook

Using examples provided in this notebook and the [official markdown syntax website](https://daringfireball.net/projects/markdown/syntax), do the following tasks.

### Tasks
1. Create a level 4 header with your name.
1. Create a ordered list with your 3 favorite books, sports teams, or music artists.
1. Type your favorite UP1 equation in LaTeX. [This page of LaTeX math symbols](http://web.ift.uib.no/Teori/KURS/WRK/TeX/symALL.html) is pretty helpful if you are new to LaTeX.
1. Create a hyperlink to the Numpy official documentation.
1. Take a picture using your phone, upload it to the assignment folder and display it in a markdown window. This is SUPER useful for project where you want to document an experimental setup or a device. Also, useful when you sketch a diagram and want to include it in a notebook.
1. Browse the [Matplotlib gallery](http://matplotlib.org/gallery.html) to find a really cool plot and display it as a *linked image* in your own notebook. You can display an image from a another website if you copy the URL.


## Jupyter keyboard shortcuts

### Tasks
1. What is the Jupyter notebook keyboard shortcut for switching a cell to Markdown mode? Try it out!
1. What is the Jupyter notebook keyboard shortcut for inserting a cell above? Try it out!
1. Browse through a list of keyboard shortcuts. What other shortcuts might you use regularly?


## Importing and plotting your own data

### Tasks
1. Install the FREE (but totally cool!) [Physics Toolbox Apps](https://www.vieyrasoftware.net/) on your own (or a classmate's) Android or iOS smartphone. 
1. Collect some data of you doing something interesting (riding in an elevator, jumping on a trampoline, **be creative and curious**) and get some measurements.
1. Upload your data to the CoCalc server for this assignment.
1. Make a well-formatted plot.
1. Explain what you were doing and interpret the data. What is going on? Was there anything interesting or surprising?

$\alpha$